/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'


export const appRoot = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/`,options
    );
  }


export const getAppRootQueryKey = () => [`/`];

    
export type AppRootQueryResult = NonNullable<Awaited<ReturnType<typeof appRoot>>>
export type AppRootQueryError = AxiosError<unknown>

export const useAppRoot = <TData = Awaited<ReturnType<typeof appRoot>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appRoot>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppRootQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appRoot>>> = ({ signal }) => appRoot({ signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof appRoot>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

