/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  AppEditProductParams,
  CreateDistributorDto,
  Distributor,
  UpdateDistributorDto,
  Product,
  GenerateExternalQrDto,
  DistributorsConfirmPaymentBody
} from '.././models'


export const appAddProduct = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/add-product`,options
    );
  }


export const getAppAddProductQueryKey = () => [`/add-product`];

    
export type AppAddProductQueryResult = NonNullable<Awaited<ReturnType<typeof appAddProduct>>>
export type AppAddProductQueryError = AxiosError<unknown>

export const useAppAddProduct = <TData = Awaited<ReturnType<typeof appAddProduct>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appAddProduct>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppAddProductQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appAddProduct>>> = ({ signal }) => appAddProduct({ signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof appAddProduct>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const appEditProduct = (
    params: AppEditProductParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/edit-product`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getAppEditProductQueryKey = (params: AppEditProductParams,) => [`/edit-product`, ...(params ? [params]: [])];

    
export type AppEditProductQueryResult = NonNullable<Awaited<ReturnType<typeof appEditProduct>>>
export type AppEditProductQueryError = AxiosError<unknown>

export const useAppEditProduct = <TData = Awaited<ReturnType<typeof appEditProduct>>, TError = AxiosError<unknown>>(
 params: AppEditProductParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appEditProduct>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppEditProductQueryKey(params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appEditProduct>>> = ({ signal }) => appEditProduct(params, { signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof appEditProduct>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const appGetAllProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/view-products`,options
    );
  }


export const getAppGetAllProductsQueryKey = () => [`/view-products`];

    
export type AppGetAllProductsQueryResult = NonNullable<Awaited<ReturnType<typeof appGetAllProducts>>>
export type AppGetAllProductsQueryError = AxiosError<unknown>

export const useAppGetAllProducts = <TData = Awaited<ReturnType<typeof appGetAllProducts>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appGetAllProducts>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppGetAllProductsQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appGetAllProducts>>> = ({ signal }) => appGetAllProducts({ signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof appGetAllProducts>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const khamFactory = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/kham/form`,undefined,options
    );
  }



    export type KhamFactoryMutationResult = NonNullable<Awaited<ReturnType<typeof khamFactory>>>
    
    export type KhamFactoryMutationError = AxiosError<unknown>

    export const useKhamFactory = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof khamFactory>>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof khamFactory>>, TVariables> = () => {
          

          return  khamFactory(axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof khamFactory>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const khamAddNewProduct = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/kham/products`,undefined,options
    );
  }



    export type KhamAddNewProductMutationResult = NonNullable<Awaited<ReturnType<typeof khamAddNewProduct>>>
    
    export type KhamAddNewProductMutationError = AxiosError<unknown>

    export const useKhamAddNewProduct = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof khamAddNewProduct>>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof khamAddNewProduct>>, TVariables> = () => {
          

          return  khamAddNewProduct(axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof khamAddNewProduct>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const khamEditProduct = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `/kham/products`,undefined,options
    );
  }



    export type KhamEditProductMutationResult = NonNullable<Awaited<ReturnType<typeof khamEditProduct>>>
    
    export type KhamEditProductMutationError = AxiosError<unknown>

    export const useKhamEditProduct = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof khamEditProduct>>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof khamEditProduct>>, TVariables> = () => {
          

          return  khamEditProduct(axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof khamEditProduct>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const khamAuthorize = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/kham/login`,undefined,options
    );
  }



    export type KhamAuthorizeMutationResult = NonNullable<Awaited<ReturnType<typeof khamAuthorize>>>
    
    export type KhamAuthorizeMutationError = AxiosError<unknown>

    export const useKhamAuthorize = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof khamAuthorize>>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof khamAuthorize>>, TVariables> = () => {
          

          return  khamAuthorize(axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof khamAuthorize>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsCreate = (
    createDistributorDto: CreateDistributorDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/distributors`,
      createDistributorDto,options
    );
  }



    export type DistributorsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsCreate>>>
    export type DistributorsCreateMutationBody = CreateDistributorDto
    export type DistributorsCreateMutationError = AxiosError<unknown>

    export const useDistributorsCreate = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsCreate>>, TError,{data: CreateDistributorDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsCreate>>, {data: CreateDistributorDto}> = (props) => {
          const {data} = props ?? {};

          return  distributorsCreate(data,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsCreate>>, TError, {data: CreateDistributorDto}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Distributor>> => {
    return axios.get(
      `/distributors/${id}`,options
    );
  }


export const getDistributorsFindOneQueryKey = (id: string,) => [`/distributors/${id}`];

    
export type DistributorsFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof distributorsFindOne>>>
export type DistributorsFindOneQueryError = AxiosError<unknown>

export const useDistributorsFindOne = <TData = Awaited<ReturnType<typeof distributorsFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof distributorsFindOne>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDistributorsFindOneQueryKey(id);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof distributorsFindOne>>> = ({ signal }) => distributorsFindOne(id, { signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof distributorsFindOne>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const distributorsUpdate = (
    id: string,
    updateDistributorDto: UpdateDistributorDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.patch(
      `/distributors/${id}`,
      updateDistributorDto,options
    );
  }



    export type DistributorsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsUpdate>>>
    export type DistributorsUpdateMutationBody = UpdateDistributorDto
    export type DistributorsUpdateMutationError = AxiosError<unknown>

    export const useDistributorsUpdate = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsUpdate>>, TError,{id: string;data: UpdateDistributorDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsUpdate>>, {id: string;data: UpdateDistributorDto}> = (props) => {
          const {id,data} = props ?? {};

          return  distributorsUpdate(id,data,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsUpdate>>, TError, {id: string;data: UpdateDistributorDto}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/distributors/${id}`,options
    );
  }



    export type DistributorsRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsRemove>>>
    
    export type DistributorsRemoveMutationError = AxiosError<unknown>

    export const useDistributorsRemove = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  distributorsRemove(id,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsRemove>>, TError, {id: string}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsGetGeneratedProducts = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product[]>> => {
    return axios.get(
      `/distributors/${id}/products`,options
    );
  }


export const getDistributorsGetGeneratedProductsQueryKey = (id: string,) => [`/distributors/${id}/products`];

    
export type DistributorsGetGeneratedProductsQueryResult = NonNullable<Awaited<ReturnType<typeof distributorsGetGeneratedProducts>>>
export type DistributorsGetGeneratedProductsQueryError = AxiosError<unknown>

export const useDistributorsGetGeneratedProducts = <TData = Awaited<ReturnType<typeof distributorsGetGeneratedProducts>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof distributorsGetGeneratedProducts>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDistributorsGetGeneratedProductsQueryKey(id);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof distributorsGetGeneratedProducts>>> = ({ signal }) => distributorsGetGeneratedProducts(id, { signal, ...axiosOptions });

  const query = useQuery<Awaited<ReturnType<typeof distributorsGetGeneratedProducts>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const distributorsGenerateQrForExternalProduct = (
    id: string,
    generateExternalQrDto: GenerateExternalQrDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    return axios.post(
      `/distributors/${id}/products/external`,
      generateExternalQrDto,options
    );
  }



    export type DistributorsGenerateQrForExternalProductMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsGenerateQrForExternalProduct>>>
    export type DistributorsGenerateQrForExternalProductMutationBody = GenerateExternalQrDto
    export type DistributorsGenerateQrForExternalProductMutationError = AxiosError<unknown>

    export const useDistributorsGenerateQrForExternalProduct = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsGenerateQrForExternalProduct>>, TError,{id: string;data: GenerateExternalQrDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsGenerateQrForExternalProduct>>, {id: string;data: GenerateExternalQrDto}> = (props) => {
          const {id,data} = props ?? {};

          return  distributorsGenerateQrForExternalProduct(id,data,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsGenerateQrForExternalProduct>>, TError, {id: string;data: GenerateExternalQrDto}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsGenerateQrForExistingProduct = (
    id: string,
    productSerial: string,
    generateExternalQrDto: GenerateExternalQrDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/distributors/${id}/products/${productSerial}/qr`,
      generateExternalQrDto,options
    );
  }



    export type DistributorsGenerateQrForExistingProductMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsGenerateQrForExistingProduct>>>
    export type DistributorsGenerateQrForExistingProductMutationBody = GenerateExternalQrDto
    export type DistributorsGenerateQrForExistingProductMutationError = AxiosError<unknown>

    export const useDistributorsGenerateQrForExistingProduct = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsGenerateQrForExistingProduct>>, TError,{id: string;productSerial: string;data: GenerateExternalQrDto}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsGenerateQrForExistingProduct>>, {id: string;productSerial: string;data: GenerateExternalQrDto}> = (props) => {
          const {id,productSerial,data} = props ?? {};

          return  distributorsGenerateQrForExistingProduct(id,productSerial,data,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsGenerateQrForExistingProduct>>, TError, {id: string;productSerial: string;data: GenerateExternalQrDto}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsPayProduct = (
    id: string,
    productId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/distributors/${id}/products/${productId}/pay`,undefined,options
    );
  }



    export type DistributorsPayProductMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsPayProduct>>>
    
    export type DistributorsPayProductMutationError = AxiosError<unknown>

    export const useDistributorsPayProduct = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsPayProduct>>, TError,{id: string;productId: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsPayProduct>>, {id: string;productId: string}> = (props) => {
          const {id,productId} = props ?? {};

          return  distributorsPayProduct(id,productId,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsPayProduct>>, TError, {id: string;productId: string}, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsConfirmPaymentWebhook = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/distributors/confirm-payment-webhook`,undefined,options
    );
  }



    export type DistributorsConfirmPaymentWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsConfirmPaymentWebhook>>>
    
    export type DistributorsConfirmPaymentWebhookMutationError = AxiosError<unknown>

    export const useDistributorsConfirmPaymentWebhook = <TError = AxiosError<unknown>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsConfirmPaymentWebhook>>, TError,TVariables, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsConfirmPaymentWebhook>>, TVariables> = () => {
          

          return  distributorsConfirmPaymentWebhook(axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsConfirmPaymentWebhook>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const distributorsConfirmPayment = (
    distributorsConfirmPaymentBody: DistributorsConfirmPaymentBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/distributors/confirm-payment`,
      distributorsConfirmPaymentBody,options
    );
  }



    export type DistributorsConfirmPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof distributorsConfirmPayment>>>
    export type DistributorsConfirmPaymentMutationBody = DistributorsConfirmPaymentBody
    export type DistributorsConfirmPaymentMutationError = AxiosError<unknown>

    export const useDistributorsConfirmPayment = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof distributorsConfirmPayment>>, TError,{data: DistributorsConfirmPaymentBody}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof distributorsConfirmPayment>>, {data: DistributorsConfirmPaymentBody}> = (props) => {
          const {data} = props ?? {};

          return  distributorsConfirmPayment(data,axiosOptions)
        }

      return useMutation<Awaited<ReturnType<typeof distributorsConfirmPayment>>, TError, {data: DistributorsConfirmPaymentBody}, TContext>(mutationFn, mutationOptions)
    }
    