/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { AddCustomAppsCategoryDtoLabels } from './addCustomAppsCategoryDtoLabels';

export interface AddCustomAppsCategoryDto {
  categoryId: string;
  labels: AddCustomAppsCategoryDtoLabels;
  index?: number;
}
