/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { AddCustomAppDtoLabels } from './addCustomAppDtoLabels';

export interface AddCustomAppDto {
  appId: string;
  value: string;
  icon?: boolean;
  enabled?: boolean;
  categoryId: string;
  labels: AddCustomAppDtoLabels;
}
