/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { AddLinksCategoryDtoLabels } from './addLinksCategoryDtoLabels';

export interface AddLinksCategoryDto {
  categoryId: string;
  labels: AddLinksCategoryDtoLabels;
  index?: number;
  enabled?: boolean;
}
