/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export interface BusinessDetails {
  businessType?: string;
  googleMapsUrl?: string;
}
