/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { PartialCreateUserDto } from './partialCreateUserDto';

export interface CreateDistributorDto {
  distributorName?: string;
  userId?: string;
  email?: string;
  password?: string;
  createUser?: PartialCreateUserDto;
}
