/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { GeoPoint } from './geoPoint';

export interface CreateEventDto {
  id?: string;
  createdAt?: string;
  date: string;
  name: string;
  creatorId: string;
  description?: string;
  activated?: boolean;
  duration?: number;
  isFeatured?: boolean;
  tags?: string[];
  category?: string;
  eventUrl?: string;
  location?: GeoPoint;
  address?: string;
}
