/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export type CreateProductDtoType = typeof CreateProductDtoType[keyof typeof CreateProductDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductDtoType = {
  CARD: 'CARD',
  STICKER: 'STICKER',
  KEYCHAIN: 'KEYCHAIN',
} as const;
