/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { PaymentEntity } from './paymentEntity';

export type DistributorsConfirmPayment201 = {
  ok?: boolean;
  payment?: PaymentEntity;
};
