/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { DistributorCount } from './distributorCount';
import type { Product } from './product';
import type { User } from './user';

export interface Distributor {
  id: string;
  _count?: DistributorCount;
  products?: Product[];
  users?: User[];
}
