/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { EditLinksCategoryDtoLabels } from './editLinksCategoryDtoLabels';

export interface EditLinksCategoryDto {
  categoryId: string;
  labels?: EditLinksCategoryDtoLabels;
  enabled?: boolean;
  index?: number;
}
