/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { EditCustomAppDtoLabels } from './editCustomAppDtoLabels';

export interface EditCustomAppDto {
  categoryId: string;
  appId: string;
  value?: string;
  icon?: boolean;
  enabled?: boolean;
  labels?: EditCustomAppDtoLabels;
}
