/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { Enterprise } from './enterprise';
import type { User } from './user';

export interface EnterpriseAccess {
  id: string;
  permissions: string[];
  role: string;
  enterpriseId: string;
  enterprise?: Enterprise;
  accessor?: User;
  accessorId: string;
}
