/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { FindAllEventsDtoTags } from './findAllEventsDtoTags';
import type { FindAllEventsDtoCategory } from './findAllEventsDtoCategory';

export interface FindAllEventsDto {
  date?: string;
  activated?: boolean;
  creatorID?: string;
  isFeatured?: boolean;
  tags?: FindAllEventsDtoTags;
  category?: FindAllEventsDtoCategory;
}
