/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export type FlagReportState = typeof FlagReportState[keyof typeof FlagReportState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlagReportState = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
} as const;
