/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { Connection } from './connection';

export interface GetUserConnectionsDto {
  connectionsInitiated?: Connection[];
  connectionsReceived?: Connection[];
}
