/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { LinkLabels } from './linkLabels';

export interface Link {
  type?: string;
  value?: string;
  enabled?: boolean;
  icon?: boolean;
  labels?: LinkLabels;
}
