/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { MetaFieldDeclarationLabels } from './metaFieldDeclarationLabels';

export interface MetaFieldDeclaration {
  labels: MetaFieldDeclarationLabels;
  type: string;
}
