/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { MetaFieldDeclaration } from './metaFieldDeclaration';
import type { MetaFieldValue } from './metaFieldValue';

export interface MetaField {
  declaration: MetaFieldDeclaration;
  value: MetaFieldValue;
  definedById: string;
  definedByCollection: string;
  lockedBy: string;
}
