/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { PartialCreateUserDtoUserType } from './partialCreateUserDtoUserType';
import type { BusinessDetails } from './businessDetails';

export interface PartialCreateUserDto {
  id?: string;
  createdAt?: string;
  firebaseUID?: string;
  email?: string;
  phone?: string;
  fullName?: string;
  userType?: PartialCreateUserDtoUserType;
  birthday?: string;
  businessDetails?: BusinessDetails;
  bio?: string;
  address?: string;
  createdById?: string;
  createdByCollection?: string;
}
