/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export type PaymentEntityGateway = typeof PaymentEntityGateway[keyof typeof PaymentEntityGateway];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentEntityGateway = {
  PAYMOB: 'PAYMOB',
} as const;
