/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export type PaymentGateway = typeof PaymentGateway[keyof typeof PaymentGateway];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentGateway = {
  PAYMOB: 'PAYMOB',
} as const;
