/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { PaymentEntityCount } from './paymentEntityCount';
import type { Product } from './product';
import type { PaymentEntityGateway } from './paymentEntityGateway';

export interface PaymentEntity {
  id: string;
  _count?: PaymentEntityCount;
  products?: Product[];
  gateway: PaymentEntityGateway;
  payerId: string;
  payerType: string;
  paymentGatewayOid: string;
  status: string;
}
