/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { ProductType } from './productType';
import type { User } from './user';
import type { Qr } from './qr';
import type { Enterprise } from './enterprise';

export interface Product {
  id?: string;
  uuid: string;
  qrUuid: string;
  type?: ProductType;
  activated?: boolean;
  ownerID?: string;
  owner?: User;
  enterpriseId?: string;
  QR?: Qr;
  enterprise?: Enterprise;
}
