/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { Qr } from './qr';
import type { ProductType } from './productType';
import type { User } from './user';
import type { Enterprise } from './enterprise';
import type { Distributor } from './distributor';
import type { Payment } from './payment';

export interface Product {
  id?: string;
  uuid: string;
  qrUuid: string;
  QR?: Qr;
  type?: ProductType;
  activated?: boolean;
  label?: string;
  ownerID?: string;
  owner?: User;
  enterpriseId?: string;
  enterprise?: Enterprise;
  generatedBy?: Distributor;
  generatedById?: string;
  payment?: Payment;
  paymentFinalized?: boolean;
  paymentId?: string;
}
