/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { UpdateEnterpriseDtoMetaFieldsDeclarations } from './updateEnterpriseDtoMetaFieldsDeclarations';

export interface UpdateEnterpriseDto {
  name?: string;
  url?: string;
  logo?: string;
  cover?: string;
  metaFieldsDeclarations?: UpdateEnterpriseDtoMetaFieldsDeclarations;
}
