/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */

export type UpdateUserDtoUserType = typeof UpdateUserDtoUserType[keyof typeof UpdateUserDtoUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserDtoUserType = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  EVENT_ORGANIZER: 'EVENT_ORGANIZER',
  BUSINESS_OWNER: 'BUSINESS_OWNER',
  DISTRIBUTOR: 'DISTRIBUTOR',
} as const;
