/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { ControlledValue } from './controlledValue';
import type { UpdateUserDtoUserType } from './updateUserDtoUserType';
import type { WorkInfo } from './workInfo';
import type { BusinessDetails } from './businessDetails';

export interface UpdateUserDto {
  createdAt?: string;
  firebaseUID?: string;
  fullName?: string;
  username?: string;
  title?: string;
  bio?: string;
  primaryEmailEnabled?: boolean;
  primaryEmail?: string;
  primaryPhoneEnabled?: boolean;
  primaryPhone?: string;
  emails?: ControlledValue[];
  phones?: ControlledValue[];
  userType?: UpdateUserDtoUserType;
  birthday?: string;
  workInfo?: WorkInfo;
  userAccentColor?: string;
  businessDetails?: BusinessDetails;
  address?: string;
}
