/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { MetaField } from './metaField';

export type UserExtraFields = {[key: string]: MetaField};
