/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * API
 * API DOCS
 * OpenAPI spec version: 1.0
 */
import type { Connection } from './connection';
import type { Product } from './product';
import type { ControlledValue } from './controlledValue';
import type { UserType } from './userType';
import type { BusinessDetails } from './businessDetails';
import type { UserLinks } from './userLinks';
import type { UserLinksCategories } from './userLinksCategories';
import type { UserTags } from './userTags';
import type { WorkInfo } from './workInfo';
import type { Enterprise } from './enterprise';
import type { EnterpriseAccess } from './enterpriseAccess';
import type { UserUserPrefs } from './userUserPrefs';
import type { UserExtraFields } from './userExtraFields';
import type { Distributor } from './distributor';

export interface User {
  title?: string;
  bio?: string;
  attendedEvents?: string[];
  connectionsInitiated?: Connection[];
  connectionsReceived?: Connection[];
  products?: Product[];
  id?: string;
  createdAt?: string;
  firebaseUID?: string;
  fullName?: string;
  username?: string;
  primaryEmail?: string;
  primaryPhone?: string;
  primaryPhoneEnabled?: boolean;
  primaryEmailEnabled?: boolean;
  emails?: ControlledValue[];
  phones?: ControlledValue[];
  userType?: UserType;
  birthday?: string;
  address?: string;
  businessDetails?: BusinessDetails;
  links?: UserLinks;
  linksCategories?: UserLinksCategories;
  tags?: UserTags;
  fcmTokens?: string[];
  workInfo?: WorkInfo;
  userAccentColor?: string;
  documentVersion?: string;
  enterpriseId?: string;
  enterprise?: Enterprise;
  enterpriseAccess?: EnterpriseAccess;
  directLink?: string;
  directLinkEnabled?: boolean;
  lockedProperties?: string[];
  userPrefs?: UserUserPrefs;
  extraFields?: UserExtraFields;
  createdById?: string;
  createdByCollection?: string;
  distributorId?: string;
  distributor?: Distributor;
}
